//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMWG_MVCApp.DB
{
    using System;
    
    public enum Country : int
    {
        None = 0,
        Türkiye = 1,
        ABD = 2,
        Kanada = 3,
        İspanya = 4,
        İngiltere = 5
    }
}
